### ISSUE TITLE
Valine comment: comment section is below "credit" section when article is long

### ISSUE THREAD

**Issue by shj37** [ppoffice/hexo-theme-hueman#271]
Even after I moved into article-inner, it is still below credit when article is long, but stay in article-inner with short post. Thank you.

Setting in article:ejs
![~7}EB)D7DPAF_RU24CSY(2K](https://user-images.githubusercontent.com/8279674/71323819-660d2d00-2512-11ea-9616-d69ad65c7714.png)

Works with short post
https://eduunited.org/2019/12/21/testcomment/
![0X%70UBWDM9XCI}GRY5CYV9](https://user-images.githubusercontent.com/8279674/71323840-a2408d80-2512-11ea-869a-6cd3f8fcc911.png)

Not work with long post
https://eduunited.org/2019/12/21/postshare/
![4~1)RNXN442O1E%){H{IT`I](https://user-images.githubusercontent.com/8279674/71323869-edf33700-2512-11ea-8900-69f7a2d318da.png)

THANK YOU.

Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [x] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [x] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki)并创建了自己的配置文件(_config.yml)；
- [x] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-hueman/issues)，并且没有找到类似的问题。

**Comment by ppoffice** [comment]
@shj37 Thank you for pointing this out. The issue should be solved with the latest commit. Please try it out.

**Comment by shj37** [comment]
> @shj37 Thank you for pointing this out. The issue should be solved with the latest commit. Please try it out.

I think you missed "<div class="vcomments"></div>" near the top

**Comment by shj37** [comment]
@ppoffice 
Thank you.
